### ISSUE TITLE
Classes not applied in FastBoot when environment=production

### ISSUE THREAD

**Issue by billdami** [mansona/ember-body-class#20]
Running on ember 3.1.2, the addon works fine, except for when I build/serve my app with `--environment=production`, I noticed that route classes are not applied to the body tag on the fastboot rendered version of the page. Once the page is re-rendered on the clientside, the classes are added correctly.

**Comment by mansona** [comment]
@billdami can you try the latest version and tell me if you're still seeing the same issue? 

Also, can you provide some sort of reproduction of this? Can you share a repo that has the issue? I've not been seeing this in any of the projects that I'm using ember-body-class with 🤔

**Comment by mansona** [comment]
@jeffjewiss I've just had a quick look and it's an interesting problem. Your issue has nothing to do with "building with environment production" so it's not strictly related to this issue, but I have been able to recreate it locally and have a fix for it.

Essentially the problem is that you have added a class to the body already with `class="sans-serif"` so it is causing some issues with the fastboot implementation. If you remove that from the index.html file it starts working again.

This is potentially something that we can write a test for and fix but if you want to fix it locally you can remove that class from your body tag and let Ember manage it 👍

**Comment by jeffjewiss** [comment]
@mansona thanks for looking into this! Sorry for creating noise on this ticket. I didn't realize it wasn't related or that having a class already on the body would cause a conflict.

I can confirm that removing the class from the body fixes my issue, thanks again!

**Comment by mansona** [comment]
@jeffjewiss I'm not entirely sure this counts as noise on the ticket 😂 It could possibly be the issue that @billdami was having but it seemed like something else.

If anyone wants to track this issue I have created a PR that has a failing fastboot test https://github.com/stonecircle/ember-body-class/pull/27

**Comment by john-griffin** [comment]
Just hit this when building an app using per page themes in fastboot. We set the theme class in the body on a specific route using ember-body-class. Serving via fastboot causes the class to be stripped out and then re-added creating a visible flicker.

**Comment by mansona** [comment]
@john-griffin is your application private? can I take a look?

**Comment by mansona** [comment]
I'm closing this since there was no response. I've also fixed a bug recently that is now tested 👍
